### ISSUE TITLE
Troubles with character encoding

### ISSUE THREAD

**Issue by lunakv** [RulesLawyerBot/ruleslawyer#14]
![2022-10-12_15-34](https://user-images.githubusercontent.com/38463785/195356912-b7a6036a-b85c-4afa-b0ac-4dcb8dd2a65b.png)

Apparently the transformation script used to convert the CR makes some incorrect assumptions about the file's character encoding :slightly_smiling_face: 

If it helps, the text file as served by WotC are encoded in WINDOWS-1252.

**Comment by elainecao93** [comment]
Thanks for the heads up!

Yeah, this has been a constant issue for me, and problems keep popping up. I just switched the environment to keep up with increased usage and I guess we're here again :(

**Comment by lunakv** [comment]
I feel ya 🙂. If you need a quick band-aid fix, I have a UTF-8 encoded version of the text file available [here](https://api.academyruins.com/file/cr/unf), though that still includes all the rich formatting (typographical quotation marks, actual trademark symbols, etc.) that I see you don't use, so I don't know how useful that really is

**Comment by elainecao93** [comment]
Fixing this in the latest release today, along with the UNF CR :)

Thanks for the heads up!
